<a href="https://colab.research.google.com/github/CivitCihan/DataScience/blob/main/DataSci2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h1>Data Analysis with NumPy 2</h1>

In [ ]:
import numpy as np

In [ ]:
a = np.array([1,2,3,4,5])
b = np.array([2.1, 7, 8, 1.2, 5])
ab = [a*b]
ab
c = np.zeros([5], dtype = int)
d = np.ones([5], dtype = int)
e = np.full([5], 7)

In [ ]:
c
d
e

array([7, 7, 7, 7, 7])

In [ ]:
c-ab*(e-d)

array([[ -12.6,  -84. , -144. ,  -28.8, -150. ]])

In [ ]:
f = np.random.randint(0, 10, (5,5))
f[3] = d
f[1] = a
f[2] = b
f

array([[2, 4, 3, 5, 5],
       [1, 2, 3, 4, 5],
       [2, 7, 8, 1, 5],
       [1, 1, 1, 1, 1],
       [5, 8, 9, 8, 5]])

In [ ]:
f.shape

(5, 5)

In [ ]:
f.size

25

In [ ]:
f.dtype

dtype('int64')

In [ ]:
f.ndim

2

In [ ]:
x = np.arange(1,10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x.reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
q = np.random.randint(10, size = 10)
z = np.random.randint(10, size = 10)

In [ ]:
zq=np.concatenate([q,z])
zq
zq=zq.reshape((2,10))

In [ ]:
qz=np.concatenate([zq, zq])
qz

array([[8, 2, 8, 6, 6, 9, 5, 0, 7, 0],
       [4, 2, 8, 5, 6, 8, 3, 8, 0, 6],
       [8, 2, 8, 6, 6, 9, 5, 0, 7, 0],
       [4, 2, 8, 5, 6, 8, 3, 8, 0, 6]])

In [ ]:
qz=np.concatenate([zq, zq], axis=1)
qz

array([[8, 2, 8, 6, 6, 9, 5, 0, 7, 0, 8, 2, 8, 6, 6, 9, 5, 0, 7, 0],
       [4, 2, 8, 5, 6, 8, 3, 8, 0, 6, 4, 2, 8, 5, 6, 8, 3, 8, 0, 6]])

In [ ]:
np.sort(qz)

array([[0, 0, 0, 0, 2, 2, 5, 5, 6, 6, 6, 6, 7, 7, 8, 8, 8, 8, 9, 9],
       [0, 0, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 6, 6, 8, 8, 8, 8, 8, 8]])

In [ ]:
qz[0][9]

0

In [ ]:
np.append(zq, qz)
# np.concatenate([zq, qz])

array([8, 2, 8, 6, 6, 9, 5, 0, 7, 0, 4, 2, 8, 5, 6, 8, 3, 8, 0, 6, 8, 2,
       8, 6, 6, 9, 5, 0, 7, 0, 8, 2, 8, 6, 6, 9, 5, 0, 7, 0, 4, 2, 8, 5,
       6, 8, 3, 8, 0, 6, 4, 2, 8, 5, 6, 8, 3, 8, 0, 6])