<a href="https://colab.research.google.com/github/CivitCihan/DataScience/blob/main/DataSci.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [ ]:
a = np.arange(2, 15)
a

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
a[0:3]

array([2, 3, 4])

In [ ]:
a[0::3]

array([ 2,  5,  8, 11, 14])

In [ ]:
a[2::5]

array([ 4,  9, 14])

In [ ]:
b = np.random.randint(10, size = (5,5))
b

array([[7, 5, 1, 9, 4],
       [8, 0, 1, 1, 0],
       [6, 0, 2, 1, 6],
       [8, 9, 6, 0, 2],
       [9, 0, 1, 5, 6]])

In [ ]:
b[0] #satır

array([ 10, 103, 103,  12,   7])

In [ ]:
b[:,4] #sütun

array([4, 0, 6, 2, 6])

In [ ]:
b[0:3, 1:4] # Satır Sütun aralığı

array([[5, 1, 9],
       [0, 1, 1],
       [0, 2, 1]])

In [ ]:
alt_b = b[0:3, 1:4]
alt_b

array([[5, 1, 9],
       [0, 1, 1],
       [0, 2, 1]])

In [ ]:
alt_b[0, 0:2] = 100
alt_b

array([[100, 100,   9],
       [  0,   1,   1],
       [  0,   2,   1]])

In [ ]:
b # alt kümlelerdeki değişiklik tüm kümeyi de etkiliyor

array([[  7, 100, 100,   9,   4],
       [  8,   0,   1,   1,   0],
       [  6,   0,   2,   1,   6],
       [  8,   9,   6,   0,   2],
       [  9,   0,   1,   5,   6]])

In [ ]:
copy_b = b[2:4, 0:4].copy()
copy_b[0:2, 0:2] = 31
copy_b

array([[31, 31,  2,  1],
       [31, 31,  6,  0]])

In [ ]:
b # Copy fonksiyonu asıl arrayden bağımsız hale getirmeyi sağlıyor

array([[ 10, 103, 103,  12,   7],
       [ 11,   0,   4,   4,   0],
       [  9,   0,   5,   4,   9],
       [ 11,  12,   9,   0,   5],
       [ 12,   0,   4,   8,   9]])

In [ ]:
b[b > 0] += 1
b

array([[ 10, 103, 103,  12,   7],
       [ 11,   0,   4,   4,   0],
       [  9,   0,   5,   4,   9],
       [ 11,  12,   9,   0,   5],
       [ 12,   0,   4,   8,   9]])

In [ ]:
b=b/2
b

array([[ 2.5 , 25.75, 25.75,  3.  ,  1.75],
       [ 2.75,  0.  ,  1.  ,  1.  ,  0.  ],
       [ 2.25,  0.  ,  1.25,  1.  ,  2.25],
       [ 2.75,  3.  ,  2.25,  0.  ,  1.25],
       [ 3.  ,  0.  ,  1.  ,  2.  ,  2.25]])

In [ ]:
a = np.array(([1,2,4,1], [2,3,8,0], [2,4,6,1], [12,7,7,-1]))
b = np.array([2,5,7,60])

In [ ]:
x = np.linalg.solve(a,b)
x

array([ 4.87951807,  1.04819277, -0.98795181, -1.02409639])

In [ ]:
[b[1], b[0]]

[5, 2]